apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: tweet-app
spec:
  replicas: 1
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ravi
        tier: tweet-app
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - image: hub.docker.com/devopscafe/tweet-app:dev-67bf09bb6210a42e15f10cc6963aa3ba6117ca5b
        name: tweet-app
        imagePullPolicy: Always
        ports:
        - containerPort: 99
          protocol: TCP
        env:
        - name: NODE_ENV
          value: dev

        resources: 
          requests:
            cpu: 50m
      restartPolicy: Always
