apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: tweet-app
spec:
  replicas: 1
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ravi
        tier: tweet-app
    spec:
      containers:
      - image: registry.hub.docker.com/devopscafe/tweet-app
        name: tweet-app

        ports:
        - containerPort: 99
          protocol: TCP
        env:
        - name: NODE_ENV
          value: dev

        resources: 
          requests:
            cpu:50m
      restartPolicy: $POLICY
